
export const coursesData = [
  {
    id: 1,
    name: 'Advanced Calculus',
    icon: 'calculator',
    category: 'Mathematics',
    description: 'Master derivatives, integrals, and differential equations',
    lessons: 24,
    xp: 15000,
    duration: '8 hours',
    level: 'Advanced',
    enrolled: true,
    progress: 68,
    rating: 4.8,
    students: 1234,
    color: 'from-blue-500 to-cyan-500',
    bgColor: 'bg-blue-100',
    iconColor: 'text-blue-600'
  },
  {
    id: 2,
    name: 'Quantum Physics',
    icon: 'atom',
    category: 'Physics',
    description: 'Explore quantum mechanics and particle behavior',
    lessons: 18,
    xp: 10000,
    duration: '6 hours',
    level: 'Advanced',
    enrolled: true,
    progress: 45,
    rating: 4.9,
    students: 892,
    color: 'from-purple-500 to-pink-500',
    bgColor: 'bg-purple-100',
    iconColor: 'text-purple-600'
  },
  {
    id: 3,
    name: 'Organic Chemistry',
    icon: 'beaker',
    category: 'Chemistry',
    description: 'Learn molecular structures and chemical reactions',
    lessons: 20,
    xp: 9000,
    duration: '7 hours',
    level: 'Intermediate',
    enrolled: true,
    progress: 82,
    rating: 4.7,
    students: 2156,
    color: 'from-green-500 to-emerald-500',
    bgColor: 'bg-green-100',
    iconColor: 'text-green-600'
  },
  {
    id: 4,
    name: 'World History',
    icon: 'globe',
    category: 'History',
    description: 'Journey through major civilizations and events',
    lessons: 30,
    xp: 12500,
    duration: '10 hours',
    level: 'Beginner',
    enrolled: true,
    progress: 30,
    rating: 4.6,
    students: 3421,
    color: 'from-orange-500 to-red-500',
    bgColor: 'bg-orange-100',
    iconColor: 'text-orange-600'
  },
  {
    id: 5,
    name: 'Linear Algebra',
    icon: 'calculator',
    category: 'Mathematics',
    description: 'Understand vectors, matrices, and transformations',
    lessons: 16,
    xp: 8000,
    duration: '5 hours',
    level: 'Intermediate',
    enrolled: false,
    progress: 0,
    rating: 4.8,
    students: 1567,
    color: 'from-indigo-500 to-blue-500',
    bgColor: 'bg-indigo-100',
    iconColor: 'text-indigo-600'
  },
  {
    id: 6,
    name: 'Astrophysics',
    icon: 'atom',
    category: 'Physics',
    description: 'Study stars, galaxies, and cosmic phenomena',
    lessons: 22,
    xp: 11250,
    duration: '8 hours',
    level: 'Advanced',
    enrolled: false,
    progress: 0,
    rating: 4.9,
    students: 678,
    color: 'from-violet-500 to-purple-500',
    bgColor: 'bg-violet-100',
    iconColor: 'text-violet-600'
  },
];

export const popularCourses = [
  {
    id: 1,
    name: 'Advanced Calculus',
    icon: 'calculator',
    category: 'Mathematics',
    description: 'Master derivatives, integrals, and differential equations',
    lessons: 24,
    xp: 15000,
    duration: '8 hours',
    level: 'Advanced',
    enrolled: true,
    progress: 68,
    rating: 4.8,
    students: 1234,
    color: 'from-blue-500 to-cyan-500',
    bgColor: 'bg-blue-100',
    iconColor: 'text-blue-600'
  },
  {
    id: 2,
    name: 'Quantum Physics',
    icon: 'atom',
    category: 'Physics',
    description: 'Explore quantum mechanics and particle behavior',
    lessons: 18,
    xp: 10000,
    duration: '6 hours',
    level: 'Advanced',
    enrolled: true,
    progress: 45,
    rating: 4.9,
    students: 892,
    color: 'from-purple-500 to-pink-500',
    bgColor: 'bg-purple-100',
    iconColor: 'text-purple-600'
  },
  {
    id: 3,
    name: 'Organic Chemistry',
    icon: 'beaker',
    category: 'Chemistry',
    description: 'Learn molecular structures and chemical reactions',
    lessons: 20,
    xp: 9000,
    duration: '7 hours',
    level: 'Intermediate',
    enrolled: true,
    progress: 82,
    rating: 4.7,
    students: 2156,
    color: 'from-green-500 to-emerald-500',
    bgColor: 'bg-green-100',
    iconColor: 'text-green-600'
  }
];

export const categories = ["Mathematics", "Physics", "Chemistry", "History"];
export const levels = ["All", "Beginner", "Intermediate", "Advanced"];
